-- Editorial venue descriptions for all 73 Published London venues
-- Updates the `description` field (NOT short_description)
-- Generated from venue audit notes, May 2026
-- Run in Supabase SQL Editor

-- ============================================================
-- SCORE 5 VENUES
-- ============================================================

UPDATE venues SET description = 'A completely alcohol-free restaurant with zero alcohol on site. The Redemption Menu runs from signature mocktails — Coco Martini, Bees Knees, Amaretti Sour — through Pierre Zero wines, all served under blossom trees with Tower Bridge views. The whole evening is built for non-drinkers: no compromises, no substitutions, no second menu. If you want a celebration dinner where the drinks programme is yours from the start, this is it.', updated_at = now() WHERE slug = 'coco-grill-lounge-london';

UPDATE venues SET description = 'Same fully alcohol-free concept as Bermondsey, relocated to a waterfront dining room at West India Quay. The Redemption Menu delivers the Coco Martini, Bees Knees, and Pierre Zero wines alongside an Anatolian-Mediterranean menu and shisha. Zero alcohol on site — the programme is the point, not an addition. Smart, high-spec interiors and the kind of evening that never requires explanation.', updated_at = now() WHERE slug = 'coco-canary-wharf-restaurant-lounge-london';

UPDATE venues SET description = 'Dishoom doesn''t have an alcohol-free section. It has a parallel drinks programme that runs twenty deep — house-made no-alcohol gin for the Sober Summer Negroni, functional shots with lion''s mane, four fresh sharbats, and Baba''s single-estate coffee. The Teetotal Tipples menu gets the same design treatment and creative energy as the alcoholic list. This is what a 5 looks like: NA isn''t a concession, it''s the point.', updated_at = now() WHERE slug = 'dishoom-london';

UPDATE venues SET description = 'The Covent Garden branch of Dishoom delivers the full Teetotal Tipples programme — twenty-plus NA serves from house-made no-alcohol gin negronis to lion''s mane functional shots, four sharbats, and Baba''s single-estate coffee. Same menu, same design treatment, same creative ambition as every Dishoom. The NA programme here isn''t a sidebar. It''s woven into the identity of the place.', updated_at = now() WHERE slug = 'dishoom-covent-garden';

UPDATE venues SET description = 'The King''s Cross Dishoom is the largest and most atmospheric of the London sites — a Bombay railway station interior that would justify a visit on its own. The Teetotal Tipples programme runs identically to every branch: twenty-plus NA serves, house-made no-alcohol gin, lion''s mane shots, sharbats, Baba''s coffee. A full evening of drinks without repetition, in a room that earns the trip.', updated_at = now() WHERE slug = 'dishoom-kings-cross';

UPDATE venues SET description = 'Dishoom Shoreditch carries the same Teetotal Tipples programme as every branch — twenty-plus dedicated NA serves including the Sober Summer Negroni with house-made no-alcohol gin, functional shots, sharbats, and single-estate coffee. The menu gets equal design treatment and creative energy. This is Bombay cafe culture where the drinks list works regardless of what you''re drinking.', updated_at = now() WHERE slug = 'dishoom-shoreditch';

UPDATE venues SET description = 'The world''s only alcohol-free metal bar. Zero alcohol on site — the entire programme is NA, from seven alcohol-free whiskeys and craft 0.0% draught beers to a metal-inspired cocktail menu, CBD drinks, kombucha, and a serious heavy-metal coffee programme. Downstairs in the Lucifer Lounge, it''s vinyl, in-store signings, and community. Raven Records proves that a bar built around music and atmosphere doesn''t need a drop of alcohol to work.', updated_at = now() WHERE slug = 'raven-records-london';

UPDATE venues SET description = 'A pub built by an alcohol-free beer brand, and it shows. Lucky Saint''s Marylebone flagship stocks nine AF beers on tap and in bottles, four AF cocktails, three AF wines, nine NA spirits, and kombucha — matched one-for-one against the alcoholic list. The Victorian pub (est. 1778, reborn 2023) feels like a proper local, not a concept store. A non-drinker here isn''t accommodated. The pub was built for them.', updated_at = now() WHERE slug = 'the-lucky-saint-london';

-- ============================================================
-- SCORE 4 VENUES
-- ============================================================

UPDATE venues SET description = 'Akoko''s soft pairing at £60 is the real story. Course by course, the beverage team matches West African spices — ehuru, uda, roselle, penja pepper — to the £130 tasting menu. Fat-washed coconut water, tamarind with penja pepper, melon with uda. Reviewers have called it preferable to the wine pairing. Three NA cocktails round it out, including a house Chapman built from hibiscus, orange, and lemon verbena. The craft here is compositional, not decorative.', updated_at = now() WHERE slug = 'akoko-london';

UPDATE venues SET description = 'Six bespoke NA alternatives sit right alongside each signature cocktail on the menu — the Currant''s Paloma riff becomes Smiling Wolf Agave and Oddbird sparkling, the Apple goes Lyre''s American Malt and Wignac Cider. Plus two standalone AF cocktails, Lucky Saint on the beer side, and a full AF spirits rack behind the bar. Former World''s Best Bar, running the "Ultimo" menu of single-ingredient preservation cocktails. The NA programme is an adaptation rather than a parallel track, but a thoughtful one.', updated_at = now() WHERE slug = 'artesian-at-the-langham-london';

UPDATE venues SET description = 'Chutney Mary doesn''t stock Seedlip or Lyre''s. It makes Indian drinks from scratch — jal jeera pani, saffron and cardamom mojito, mango mojito — using the same spice and botanical vocabulary as the Pukka Bar''s alcoholic programme. Wild Idol sparkling and Lucky Saint cover wine and beer. Small programme, six options, but the craft shares DNA with a kitchen that''s been running for thirty-five years. The NA drinks taste like they belong here because they were born here.', updated_at = now() WHERE slug = 'chutney-mary-london';

UPDATE venues SET description = 'Twelve seats around an open kitchen beneath The Blue Posts pub. The No & Low pairing — £50 at lunch, £60 at dinner — is built by the beverage team and changes with the seasons. Quince and sobacha tea with peppercorn, gooseberry and jalapeno, redcurrant and hibiscus. A Half & Half option lets you alternate wine and NA serves across the tasting menu. Guests report the NA pairings stole the show. Counter dining at its most intimate, with drinks that match.', updated_at = now() WHERE slug = 'evelyns-table-london';

UPDATE venues SET description = 'The £85 alcohol-free tasting pairing sits on the menu as a structural peer to the £155 wine pairing and the £555 Cali Burgundy. Sommelier Nadia Khan composes a multi-course AF journey matched to the £199 tasting menu. The wine list dedicates page 34 to "Abstain for Good Reason — Clarity of Mind" — eleven NA options across sparkling, white, rose, red, and sweet, with French Bloom, Jukes, Feral, and NON by the glass. A non-drinker gets the same evening as a wine drinker. The gap is structural parity.', updated_at = now() WHERE slug = 'frog-by-adam-handling-london';

UPDATE venues SET description = 'The craft ceiling here is arguably the highest in London. Smoked camel milk, hummingbird nectar, bear beer, fermented nettles, spite cordial — Lyaness''s house-made ingredients exist nowhere else and are the product of serious R&D. Five of twelve collaboration cocktails have a boozeless path, all at £9.50. When you order boozeless, you''re drinking the bar''s intellectual property, not a commercial spirit swap. The programme is structurally limited — Classics and Special Editions are alcohol-only — but the craft in what exists is undeniable.', updated_at = now() WHERE slug = 'lyaness-london';

UPDATE venues SET description = 'Mikkeller brews their own NA beers — ten proprietary styles across wheat ale, IPA, pilsner, and the Limbo sour line, including one made with juice from Mikkeller''s own vineyards. Multiple NA options rotate through the twenty taps alongside the full-strength range. No NA cocktails or wine, but for a taproom, beer is the programme, and Mikkeller''s NA range participates at the same craft level as everything else on the wall. Walk-in, industrial-chic Shoreditch taproom, deep fridge of cans.', updated_at = now() WHERE slug = 'mikkeller-bar-london';

UPDATE venues SET description = 'Mr Fogg''s runs a consistent NA formula across its ten London venues: two chain-standard cocktails (Spicy Rupee with Smiling Wolf and chipotle hibiscus, Elskling with elderflower and lavender) plus venue-specific builds using Everleaf, Seedlip, Caleno, and Martini Vibrante. NA versions integrated alongside alcoholic counterparts in themed room sections rather than separated into a mocktails section. French Bloom and Wild Life Botanicals sparkling by the bottle, AF beer at most locations. Immersive Victorian maximalism — the group scores on consistency and integration, not on craft.', updated_at = now() WHERE slug = 'mr-foggs-london';

UPDATE venues SET description = 'Only three NA cocktails — but each one is world-class. Back to My Roots involves house-made carrot syrup (peeled, blended, strained), caramel air, and two hours of prep. Southern Light needs four hours for the grapefruit and kumquat sherbet. Every NA drink gets the same double-page recipe spread as the alcoholic programme. This is what craft means at the Punch Room: process-identical to the rest of the menu. Wood-panelled cocktail den inside The London EDITION, technique-forward, intimate.', updated_at = now() WHERE slug = 'punch-room-at-the-london-edition-london';

UPDATE venues SET description = 'London''s only three-Michelin-star restaurant offers sommelier-composed NA pairings at £75 and £85, listed as structural peers alongside the wine pairings on a 62-page list. Martin Kleveta''s sommelier team curates eight NA by-the-glass options — Copenhagen Sparkling Tea, Saicho, Jukes Cordialities — in a dedicated section. The craft lives in the pairing composition, not the individual pours. For a non-drinker, the full-evening progression at Royal Hospital Road is the same as for anyone else at the table.', updated_at = now() WHERE slug = 'restaurant-gordon-ramsay-london';

UPDATE venues SET description = 'Part of the Lyan group (same owner as Lyaness), and the house craft carries over: hopped pineapple, banana cultured cream, plum wood, coriander seed cordial. Five boozeless cocktails sit in a dedicated section — the Banana Butter Swizzle with Botivo and banana cultured cream is the standout. Bases lean more commercial than Lyaness (Everleaf, Botivo, Sylva Orchard), but the modifiers are genuinely house-made. Neighbourhood Shoreditch bar, relaxed, rotating menus. Craft-assisted rather than craft-originated, but real.', updated_at = now() WHERE slug = 'seed-library-london';

UPDATE venues SET description = 'Five seasonal soft drinks, all house-made from raw ingredients. Cinchona bark tonic water — Skye Gyngell''s team actually sources the bark and makes tonic from scratch. Amalfi coast lemonade, house ginger beer, loquat and verbena with house cordial. Zero commercial NA brands. The drinks follow the same seasonal clock as the food: loquat appears in May because that''s when loquats ripen. This is a Michelin Green Star kitchen applying its from-scratch, produce-led philosophy to everything on the menu, including what non-drinkers are offered.', updated_at = now() WHERE slug = 'spring-london';

UPDATE venues SET description = 'At least two AF cocktails — Dragon Prince, Society of Exploration — are built entirely from scratch with no commercial NA spirit bases: lemongrass and ginger tea, elderflower, bergamot essence, dragon fruit and mango cooler. The Velvet Rouge layers Vault aperitif with house cardamom cordial and Wild Idol Blanc. Plus a £45 Botanical Cocktail Atelier — a private AF masterclass with canapes, the only venue in the directory offering an experience-level NA investment. AF sparkling wine, Lucky Saint, Guinness 0%. The equestrian-themed bar opposite Kensington Palace delivers more NA craft than its understated menu format suggests.', updated_at = now() WHERE slug = 'stables-bar-london';

UPDATE venues SET description = 'Best-in-class integration. Four 0% cocktails sit within the main cocktail sections — Bright, Delicate, Rich, Stiff — alongside alcoholic drinks, not quarantined into a mocktails page. Pink grapefruit sherbet, sandalwood, peppercorn, egg white: genuine bartender thinking. NA wine by glass and bottle (Torres Natureo red and white), Bitburger Drive on the beer side, two Saicho sparkling teas. Multi-award-winning Soho cocktail bar, two floors, jazz downstairs. Swift treats NA with the same respect it gives everything else, which is the whole point.', updated_at = now() WHERE slug = 'swift-london';

UPDATE venues SET description = 'Five NA cocktails on a dedicated menu page — Sweet Skulduggery, Tropic Sour, Melisa Cobbler, Forbidden Forest, Inauguration — using Everleaf, Seedlip, and Wild Idol AF sparkling. Creative builds at £10-15, on a separate Non-Alcoholic Drinks page with the same design treatment as the alcoholic programme. Tattu is theatrical modern Chinese dining on a Covent Garden rooftop with skyline views. The NA list is a genuine parallel track, not a footnote to the cocktail menu.', updated_at = now() WHERE slug = 'tattu-london-london';

UPDATE venues SET description = 'The ambient tea pairing is Forbes-featured and served in wine glasses at room temperature — a deliberate sensory choice, not a soft-drinks afterthought. Cold-infused teas alongside bespoke NA cocktails like a house take on Irn Bru and a pear-rice build, all designed in-house. For a two-Michelin-star tasting menu inside Shoreditch Town Hall, the pairing is the drinks programme. A non-drinker gets a complex, grown-up parallel experience alongside £225 wine pairings. Isaac McHale''s kitchen extends its creative process to what you drink.', updated_at = now() WHERE slug = 'the-clove-club-london';

UPDATE venues SET description = 'Home of the Martini trolley, ranked among the world''s best bars for years running. Ago Perrone''s team builds dedicated NA cocktails — Faraway Collins with house eucalyptus syrup, Maestrale with Feral Botanical Ferment, Supernature with Three Spirit Nightcap and lemon verbena. Seasonal rotation means NA is part of the creative cycle, not a static afterthought. Bespoke NA drinks available on request. Lucky Saint and two other AF beers on the list. The programme is structurally limited against 80+ years of cocktail history, but the craft standard is unmistakable.', updated_at = now() WHERE slug = 'the-connaught-bar-london';

UPDATE venues SET description = 'Five NA cocktails designed by Olly Smith — wine expert, TV personality — with a full-page dedication including photo, bio, and signature in the menu. That''s the same treatment you''d give a guest chef or spirits collaboration. Rooibos Tea Punch, Cherry Blossom with yuzu, Blackberry Buzz with spice. £16 cocktails sit naturally alongside £18-26 alcoholic signatures. UNLTD lager and IPA on the beer side, Seedlip behind the bar. Boutique hotel cocktail bar in The Mayfair Townhouse, intimate and well-judged.', updated_at = now() WHERE slug = 'the-dandy-bar-london';

UPDATE venues SET description = 'Four 0% cocktails integrated alongside alcoholic versions within an art-movement-themed menu — Realist, Impressionist, Cubist, Abstract — not separated into a mocktails section. Home-made blueberry syrup and lime-and-mint cordial from surplus products carry into the NA builds. Wild Idol sparkling by glass and bottle, six AF spirits, Peroni 0%. B-Corp products, low-waste cordials, sustainability woven through the programme. Boutique Belgravia hotel with a £35 minimum spend and genuine structural commitment to NA.', updated_at = now() WHERE slug = 'the-hari-bar-london';

UPDATE venues SET description = 'The most comprehensive NA programme in the London directory. Nine bespoke AF cocktails with original names, nine AF spirits as standalone pours, five Noughty wines by glass and bottle (red, white, rose, sparkling), two AF beers, Seasn NA bitters throughout. The programme extends into afternoon tea — Noughty sparkling as a champagne alternative, NA cocktails with the scones. Every daypart from breakfast to dinner, covered. Grand European cafe on Piccadilly, open since 2003, and the NA list is invisible until you look for it. No marketing, no press coverage. Just twenty-five AF items quietly doing the work.', updated_at = now() WHERE slug = 'the-wolseley-london';

UPDATE venues SET description = 'Minimalist, technique-forward. Four 0% cocktails at £11 — same price as the alcoholic list — using Opius and Midi Ruby spirits with serious ingredients: verjus, cubeb pepper, miso, apple vinegar, egg white. The Negroni 0% with juniper and cubeb pepper, the Whisky Sour 0% with waikato tea and oak, the Espresso Martini 0% with cacao nib and miso. Printed on the menu, not off-menu. Small, understated Dalston neighbourhood bar where the NA programme has genuine creative parity. Now also in Soho.', updated_at = now() WHERE slug = 'three-sheets-london';

UPDATE venues SET description = 'The Soho outpost of Three Sheets carries the same menu as Dalston — four 0% cocktails at £11 with Opius, Midi Ruby, verjus, cubeb pepper, miso, and egg white. Same price as the alcoholic list, same technique-forward approach, printed on the menu. The Negroni 0% and Whisky Sour 0% are standouts. Understated neighbourhood cocktail bar energy transported to Old Compton Street.', updated_at = now() WHERE slug = 'three-sheets-soho';

-- ============================================================
-- SCORE 3 VENUES
-- ============================================================

UPDATE venues SET description = 'Ten dedicated NA options is generous quantity. The house-made 34 Signature Cola (Madagascan vanilla, caramel, citrus, secret spice blend) and palo santo agave show real craft. But roughly half the menu is juice-and-tea builds with no NA spirit base, and "Virgin Mojito" and "Virgin Colada" labelling dates the programme. The craft is unevenly applied — some genuine invention alongside some filler. Mayfair power dining with Ronnie Scott''s jazz collaboration and a NA list that''s better than it first appears.', updated_at = now() WHERE slug = '34-mayfair-london';

UPDATE venues SET description = 'Three mocktails plus the largest NA spirits inventory of any single venue in the audit — nine standalone pours across CleanCo, Martini, Pentire, Seedlip, and Everleaf. Lucky Saint on draught. A dedicated fresh juice programme rounds it out. Mediterranean all-day restaurant at The Hoxton Southwark, ground floor, casual and well-stocked. Every drink is built on commercial bases, but the breadth of what''s available means you won''t run out of options.', updated_at = now() WHERE slug = 'albie-southwark';

UPDATE venues SET description = 'A ball-pit cocktail bar with seven zero-ABV options and Lucky Saint on the beer side. The Coastal Fire (Pentire, pineapple, mango, habanero, lime) and Tide Cooler show someone is paying attention to the NA space — Pentire, Everleaf, Lyre''s, Three Spirit all stocked. Dedicated menu page with its own illustrations. You''re here for the ball pit and the party, but the NA list is legitimately better than it needs to be. Low-ABV and zero-ABV mixed in the same section without clear separation — check if you need strict AF.', updated_at = now() WHERE slug = 'ballie-ballerson-london';

UPDATE venues SET description = 'Four curated NA options treated with the same care as the natural wine list — Blurred Vines Sharp and Spark from London, a 2022 Nibiru grape juice from Kamptal, Botivo botanical aperitif and soda. Independent producers, specific vintages, proper glassware. Small but intentional. No house-made elements, no cocktails — this is curation, not creation. Natural wine bar on Kingly Street in Soho (not Notting Hill as sometimes listed), with emerald interiors and a terrace.', updated_at = now() WHERE slug = 'bar-crispin-london';

UPDATE venues SET description = 'A 1940s speakeasy inside an abandoned underground station, and the NA programme keeps pace with the theme. Six Cahoots Classics have NA versions — Elizabeth II with Smiling Wolf rum, Winston Churchill with Caleno and Everleaf, Keep Marm and Carry On with orange marmalade and Crodino. Four NA beers, three NA sparklings, six commercial spirit brands. Better breadth than most venues at this score. Kingly Court, Soho, wartime newspaper menus, live swing on weekends.', updated_at = now() WHERE slug = 'cahoots-underground-london';

UPDATE venues SET description = 'Three NA cocktails and two AF wines in a beautiful 35-page drinks booklet with the same supplier storytelling as the alcoholic programme. Lively Spritz with Three Spirit and Genie apple kombucha, Deep Dark Wood with valerian and ashwagandha, Days Lager and Days Pale Ale. Breadth across every category — cocktails, wine, spirits, beer, kombucha. Values-driven Hammersmith restaurant championing independent London suppliers. The curation is impressive; the craft is commercial.', updated_at = now() WHERE slug = 'cellar-at-kindred-london';

UPDATE venues SET description = 'Five NA cocktails at £15 and Wild Idol sparkling by the glass — a dedicated section, clearly labelled, with premium commercial bases like Seedlip and Tanqueray 0.0%. It''s intentional. But the gap between this and the alcoholic programme — 88 pages of champagne, the Claridge''s Cocktail Book, fat-washing techniques — is impossible to ignore. You won''t feel like an afterthought, but you''ll know the craft went elsewhere.', updated_at = now() WHERE slug = 'claridges-bar-mayfair';

UPDATE venues SET description = 'Dante NYC crosses the Atlantic and brings three NA cocktails along — Pineapple Sgroppino with fluffy pineapple technique, NA Cosmojito with house Dante cranberry, and an Espresso Shakerato that''s essentially a dressed-up coffee. Dedicated "Non-Alcoholic" section on the cocktail menu, Wild Idol sparkling by the glass. Hints of Dante''s craft (the fluffy pineapple, the house cranberry) but thin against 25+ alcoholic cocktails including nine bespoke negroni variants and a Caviar Martini. The gap between what Dante can do and what they''ve applied to NA is enormous.', updated_at = now() WHERE slug = 'claridges-restaurant-mayfair';

UPDATE venues SET description = 'Eight NA cocktails at Oxford Circus — a shared chain menu offering The Mocktail Club section (Crodino Spritz, Strawberry Spritz, Pina Con-Nada, Alojito) plus the High & Dry range built with Smiling Wolf zero-alcohol mood-enhancing spirits. The High & Dry concept — NA base with an optional alcohol shot on the side — is genuinely smart for their audience. Loud basement party bar energy, but someone clearly put thought into making the NA menu work within it.', updated_at = now() WHERE slug = 'cocktail-club-oxford-circus';

UPDATE venues SET description = 'Same Cocktail Club chain menu as Oxford Circus — eight named NA serves across The Mocktail Club and High & Dry sections, Smiling Wolf spirits, Crodino, Real Drinks sparkling tea. The High & Dry concept (NA base, optional alcohol shot) works well for the party-bar format. Shoreditch basement, full-tilt energy, birthdays and hen dos. The NA list is more considered than the venue''s "bars that party" identity would suggest.', updated_at = now() WHERE slug = 'cocktail-club-shoreditch';

UPDATE venues SET description = 'Five NA cocktails and a homemade tonic water in the dedicated Non-Alcoholic section. The oleo saccharum and apple-and-lemongrass cordial show house touches. But the craft gap is stark — the alcoholic side does cocoa hazelnut fat-washing, house infusions, tinctures, and milk punch. None of that carries over to the NA builds, which rely on Everleaf, Seedlip, and Pathfinder. No AF wine, beer, or sparkling despite an extensive list. Firmdale''s colourful Soho hotel bar with art-inspired cocktails and a NA programme that could be much more.', updated_at = now() WHERE slug = 'ham-yard-hotel-london';

UPDATE venues SET description = 'Four Surrealist-themed NA cocktails — The Red Tower after De Chirico, A Moment of Calm after Max Ernst — using Everleaf and Seedlip. The drinks follow the same artistic concept as the alcoholic programme, which is a nice structural touch. Promoted during Dry January, confirmed on the bar menu. Not clear whether they''re on the physical menu year-round. Intimate 1920s American bar inside The Beaumont, Mayfair. Bourbon and whisky focus, terrace, old Manhattan energy.', updated_at = now() WHERE slug = 'le-magritte-bar-london';

UPDATE venues SET description = 'Three NA cocktails with dedicated names — Guava Smash, Earl of Islington, Who Said That? Where''s Kevin? — plus a Pavari 17 (a niche 2025 NA aperitif that won "Non-Alcoholic of the Year" at USA Spirit Ratings). House-made mango and green tea shrub, matcha honey foam. Seasonal rotation confirmed. From the founder of Callooh Callay, with sister bars running the same NA commitment group-wide. Intimate Islington cocktail bar, Alice in Wonderland inspired, stronger on craft signals than the drink count suggests.', updated_at = now() WHERE slug = 'little-bat-london';

UPDATE venues SET description = 'Six NA cocktails across a dedicated Apothecary-themed section — chilli-infused elderflower cordial, pumpkin spiced syrup, Nonsuch shrub — plus Spicy Rupee and Elskling from the Mr Fogg''s chain standard. All £14, matching the alcoholic range. Builds are slightly more interesting than other Fogg''s branches, though bases remain commercial (Seedlip, Everleaf, Caleno, Martini Vibrante). Victorian immersion, theatrical decor, Mayfair.', updated_at = now() WHERE slug = 'mr-foggs-apothecary-mayfair';

UPDATE venues SET description = 'Two NA punches available in sharing sizes (single, double, four-person) plus Spicy Rupee and Elskling from the chain standard. Caleno, Everleaf, Martini Vibrante behind the builds. The sharing punch format — available in the same three sizes as the alcoholic version — is a nice touch for a tavern focused on communal drinking. Fitzrovia, botanical theme, commercial NA bases, consistent with the wider Mr Fogg''s formula.', updated_at = now() WHERE slug = 'mr-foggs-botanical-tavern-fitzrovia';

UPDATE venues SET description = 'Identical menu to Mr Fogg''s Hat Tavern — two NA punches in sharing sizes, Perfect Timing and Elskling cocktails, Wild Life Botanicals sparkling, Stella 0.0% and UNLTD IPA. Also has a Games Parlour with the same drinks available. Commercial bases, thoughtful assembly, Liverpool Street location. Consistent Mr Fogg''s formula applied to the City.', updated_at = now() WHERE slug = 'mr-foggs-city-tavern-liverpool-street';

UPDATE venues SET description = 'Two NA cocktails — Bombay with Caleno coconut tropical, almond, and coconut milk; Hong Kong with Everleaf, morello cherry, and cream-and-strawberry foam — plus the chain-standard Spicy Rupee and Elskling. Four total. The smallest NA offering across the Mr Fogg''s empire, but the builds are thoughtful. Covent Garden, gin parlour theme, no AF beer or sparkling visible on the menu.', updated_at = now() WHERE slug = 'mr-foggs-gin-parlour-covent-garden';

UPDATE venues SET description = 'Two NA punches and two NA cocktails — identical to other Mr Fogg''s tavern-format venues. Punch & Juicy and A Fruity Punchline in sharing sizes, Perfect Timing with chipotle chilli and hibiscus, Elskling with elderflower and lavender. Wild Life Botanicals sparkling, Stella 0.0%, UNLTD IPA. Soho location with Smiling Wolf and Everleaf behind the bar. Consistent, commercial, competent.', updated_at = now() WHERE slug = 'mr-foggs-hat-tavern-soho';

UPDATE venues SET description = 'One bespoke NA cocktail (tropical, with Caleno, mango-and-strawberry shrub, and chocolate), one NA teapot serve for two (Everleaf, bergamot, Earl Grey tea syrup, orange marmalade), plus the chain-standard Spicy Rupee and Elskling. The teapot-for-two format adds a social dimension that mirrors the venue''s signature sharing serves. Soho, pawnbroker theme, commercial bases, Earl Grey tea syrup is the most interesting house touch.', updated_at = now() WHERE slug = 'mr-foggs-pawnbrokers-soho';

UPDATE venues SET description = 'Five NA cocktails in a dedicated section — Spicy Rupee and Elskling from the chain standard plus three bespoke to this location, including a Victorian-themed Velvet Boudoir with house caramelised pineapple and ginger shrub. NA versions integrated alongside alcoholic counterparts in themed room sections. French Bloom and Wild Life Botanicals sparkling, Stella 0.0%, UNLTD IPA. The original Mr Fogg''s, Mayfair, immersive Victorian maximalism. Calorie counts on NA but not alcoholic versions subtly signals different treatment.', updated_at = now() WHERE slug = 'mr-foggs-residence-mayfair';

UPDATE venues SET description = 'Six NA cocktails plus Wild Life Botanicals sparkling — the strongest NA count of any Mr Fogg''s venue. Dedicated section with exploration-themed builds (Forty-Niner, Santa Fe Railroad, The Cart) using Seedlip, Caleno, Everleaf, and Martini Vibrante. All £12. Commercial bases assembled with shrubs, syrups, and sherbet. Covent Garden, adventure-club theming, solid if formulaic.', updated_at = now() WHERE slug = 'mr-foggs-society-of-exploration-covent-garden';

UPDATE venues SET description = 'Two NA punches in sharing sizes (up to four-person bowls at £44) plus Spicy Rupee and Elskling. Stella 0.0% and UNLTD IPA on the beer side. The sharing punch format gives NA drinkers parity with the venue''s signature communal serves. Covent Garden tavern theme, commercial bases throughout, consistent with the wider chain.', updated_at = now() WHERE slug = 'mr-foggs-tavern-covent-garden';

UPDATE venues SET description = 'Four NA cocktails in a dedicated section — No Tai with Feragaia, Virgin Picante with Almave (Lewis Hamilton''s NA tequila), French Lady with Seedlip, plus Crodino as an aperitif and Lucky Saint on draught. The NA spirit picks are more interesting than most: Feragaia is a niche Scottish botanical spirit, Almave is barely stocked anywhere. Art Deco banking hall in The Ned, Grade I listed, verdite-green marble columns. Classic American cocktail bar with above-average NA brand curation.', updated_at = now() WHERE slug = 'nickel-bar-city';

UPDATE venues SET description = 'Six NA cocktails — dedicated section on page 38, all £12 — with names like Libre, Midori, Picon Leger, Julep Elixir. Black cardamom caramel, coconut orgeat, plant-based vitamin D extract. Better creative ambition than most venues at this score. But all bases are commercial (Seedlip, Lyre''s, Everleaf, Opius), and Nightjar''s legendary alcoholic programme uses house-made everything. The NA section doesn''t match that process. Speakeasy since 2010, live jazz nightly, reservations essential. Strong for a 3.', updated_at = now() WHERE slug = 'nightjar-london';

UPDATE venues SET description = 'Three NA cocktails get the same treatment as everything else on the menu — numbered entries, antique maps, botanical illustrations, flavour notes. Abyssinia uses African purple basil, Atacama Sour uses rica rica syrup from the Chilean desert, Caloocan Cooler uses lemongrass beer. The presentation is 4-level; the volume (three drinks, all commercial bases) keeps it at 3. Elite cocktail bar from the Nightjar team, two venues — Bamboo Bar for walk-ins, basement for reservations and live jazz. Price parity at £12.', updated_at = now() WHERE slug = 'oriole-london';

UPDATE venues SET description = 'Six themed NA cocktails — Sinless Colada, Forbidden Eden, Free Fashioned — with popping candy, smoked cherrywood, and commercial Everleaf bases throughout. The Free Fashioned mirrors the alcoholic PB Old Fashioned using the same demerara syrup and smoke technique, which is a genuine parity signal. But the £9 vs £13-16 price gap and "Mocktails" label tell you where NA sits in the hierarchy. Purgatory-themed cocktail bar in Pimlico with Japanese sushi counter and escape rooms attached.', updated_at = now() WHERE slug = 'purgatory-bar-london';

UPDATE venues SET description = 'Four "Sober Sips" on a dedicated double-page spread with the same art-forward illustrated design as the alcoholic pages. Melon seed orgeat (house-made — no commercial version exists) in the Mahiki, Three Spirits and Lyre''s behind the rest. Plus a bottomless mocktail brunch at £25 for ninety minutes. Peroni 0.0% on the beer side. Twelfth-floor rooftop with 360-degree London views. The presentation parity is excellent; the drinks themselves lean on two commercial brands.', updated_at = now() WHERE slug = 'savage-garden-rooftop-bar-london';

UPDATE venues SET description = 'Three NA cocktails integrated into the bird-themed cocktail list — Hatchling, Hummingbird, Spoonbill — with the same naming convention as the alcoholic range. Pentire and Martini Vibrante behind the builds. Lucky Saint and Siren Soundwave IPA on the beer side. Fourteenth-floor rooftop at The Hoxton Southwark, oyster bar, City views. Good integration, commercial bases, enough to get through an evening without repeating.', updated_at = now() WHERE slug = 'seabird-southwark';

UPDATE venues SET description = 'Dedicated page with six named drinks, Lucky Saint, and an Everleaf spirit-swap offer for any cocktail on the menu. Two-for-one during happy hour — same deal as alcoholic cocktails. But four of six drinks are pure juice builds with no NA spirit base, and only one brand (Everleaf Marine) appears across the entire programme. Chain party bar with fifteen London locations, karaoke rooms, shot bats, and cocktail teapots. The NA page exists and it''s inclusive, but the build quality is bottom-tier for this score.', updated_at = now() WHERE slug = 'simmons-bar-london-3';

UPDATE venues SET description = 'Eight named NA serves across two dedicated sections — The Mocktail Club (Crodino Spritz, Strawberry Spritz, Pina Con-Nada, Alojito) and High & Dry (Pornstar Puff, Bullfrog, Pineapple Express, Woodstock) built with Smiling Wolf zero-alcohol mood-enhancing spirits. The High & Dry concept — NA base with an optional alcohol shot on the side — is smart for a party bar. Self-described as "Bars That Party" and "booze-fuelled circus," but the NA menu shows someone took time to make it work for everyone.', updated_at = now() WHERE slug = 'the-cocktail-club-london';

UPDATE venues SET description = 'Ten NA serves using seven distinct premium brands — Three Spirit, Everleaf, Opius, Smiling Wolf, Rebels 0.0%, Saicho, Bemusa — plus a properly crafted Feliz Paloma with Clean Co tequila. Striking coral-pink Art Deco interior in The Bloomsbury Hotel. The breadth and curation are impressive and the "Wellness" section has its own dedicated positioning. But most serves are two-ingredient pours — spirit plus mixer — not multi-component cocktails. Only the Feliz Paloma is a real build. Curation, not composition.', updated_at = now() WHERE slug = 'the-coral-room-london';

UPDATE venues SET description = 'Four "Spirit Free" cocktails in the Bright Young Things menu — Regal Tea Sparkle with The Pathfinder and Earl Grey, Toronja Rosa with CleanCo rhubarb, Clean Cutter, Quinquina with Abstinence Lemon Aperitif. Plus Lucky Saint 0.05%. The Spirit Free section gets the same Jazz Age illustration treatment as the alcoholic pages, which is genuinely on-brand. Former smoking lounge turned cocktail bar, Rene Lalique panel from 1931, bespoke glassware. The presentation is right; the builds are standard commercial-base assemblies.', updated_at = now() WHERE slug = 'the-fumoir-mayfair';

UPDATE venues SET description = 'Three "Exciting Drinks (With No Alcohol)" at £15 — Floral with Everleaf and peppermint cordial, Mr Green with Seedlip and matcha, Fruity Old Devil with Opius and apricot. Plus Wild Idol Rose sparkling by the glass and bottle. Not "mocktails" — the labelling is a nice touch. Equal pricing to the alcoholic range. But only three cocktails, no house-made elements, and a small section on a much larger champagne-and-cocktail menu. Recently refurbished Belgravia hotel bar with conservatory, garden views, and live jazz on Sundays. You''ll be fine, but you won''t have a varied evening.', updated_at = now() WHERE slug = 'the-goring-bar-london';

UPDATE venues SET description = 'Eight "Mocktails" at £16 across a dedicated page — Clean No-groni, Clean Island Dream, Spritz Sparkle, Bellini Softini among them. Plus Peroni 0.0%, CleanCo spirits, and Noughty sparkling. Impressive quantity. But three of the eight are juice-and-soda builds with no NA spirit base, and the labelling is "Mocktails." The Library Bar sits inside The Lanesborough with an extensive whisky collection and £20 minimum spend after 7:30pm. The NA intent is clear; the craft doesn''t match the room''s reputation.', updated_at = now() WHERE slug = 'the-library-bar-london';

UPDATE venues SET description = 'Two properly crafted NA cocktails — Souk (inspired by Diriyah, Saudi Arabia, with Lyre''s, Medjool dates, raisins, hibiscus, mint) and Iridescence (inspired by Harbin Ice Festival, with jasmine tea, lychee, yuzu caviar, glitter) — each getting a full-page spread with travel narrative. Same creative storytelling as the alcoholic signatures. But only two out of twelve means you exhaust the NA menu in two rounds. Wild Idol sparkling, five AF spirits, Peroni 0.0% on the beverage list. Glamorous Mayfair hotel bar where the quality is high and the quantity is not.', updated_at = now() WHERE slug = 'the-may-fair-bar-london';

-- ============================================================
-- SCORE 2 VENUES
-- ============================================================

UPDATE venues SET description = 'Three "Virgin Cocktails" at £11 — Essenza, Euphoria, Ananas & Menta — using 0% amaro and gin with cordials. Dedicated section on the menu, Italian-themed builds. But "Virgin Cocktails" frames NA as derivative, and the £11 price tag (vs £14 alcoholic) signals a tier below. Commercial bases, simple builds. Good Italian cocktail bar in Soho for Negroni and Spritz. If you''re not drinking, you have three options and a subtle reminder that the menu wasn''t built for you.', updated_at = now() WHERE slug = 'bar-lina-london';

UPDATE venues SET description = 'Two NA spritzes (Crodino, Pathfinder) and three low-alcohol beers with a labelled "Low & No" section. Decent for a pub — commercial products served well, rotating NA draught option. But no crafted NA cocktails, no house-made anything. Earl''s Brewery beers on site, eleven keg lines, five cask beers. The beer is the story and the NA beer is fine. Not a destination for non-alcoholic drinks, but you won''t be stuck with a Coke.', updated_at = now() WHERE slug = 'earl-of-essex-london';

UPDATE venues SET description = 'Three parenthetical AF versions of alcoholic cocktails — "(£13 alcohol-free)" appended to the menu with no detail on what the AF versions actually contain. No dedicated section, Seedlip stocked but unused in cocktails, no NA beer, wine, or sparkling. The house-made cordials (Sage, Mint Harmony) probably make the AF versions taste decent, but you can''t verify from the menu. Eleventh-floor rooftop with Tower of London views. The venue had standalone NA cocktails at launch and has since regressed.', updated_at = now() WHERE slug = 'florattica-rooftop-london-london';

UPDATE venues SET description = 'The NA capability exists — Sentia non-alcoholic spirits behind the bar, bartenders can make bespoke drinks, mentioned in Dry January guides. But none of it appears on the actual menu. A non-drinker sees fifteen mezcal-heavy cocktails, a seven-drink Martini Menu, and zero listed NA options. You have to ask. Being mentioned in guides is PR, not programme. Trendy Mayfair cocktail bar with rotating pop-up kitchens and live music.', updated_at = now() WHERE slug = 'jazu-london';

UPDATE venues SET description = 'One confirmed NA cocktail — a Botivo and ginger beer mocktail at the casual Cafe venue. No evidence of any programme at the main restaurant, where the focus is a 217-label all-Italian wine list. One TripAdvisor reviewer''s wife got "a lemonade with a strawberry blended in it — £15." Iconic Italian since 1987, Thames-side in Hammersmith, legendary produce. The kitchen is world-class. The NA offering is not.', updated_at = now() WHERE slug = 'the-river-caf-london';

UPDATE venues SET description = 'Two Pentire drinks — a Coastal Spritz (Pentire, tonic, orange) and an Adrift Margarita (Pentire, agave, lime, chilli) — under a dedicated section header with only two options underneath. Plus Bero 0.5% beer. A venue whose entire identity is apothecary craft — Tony Conigliaro''s legacy of homemade syrups, cordials, tinctures, lab distillations — has put zero of that into NA. Two simple Pentire builds is the definition of checkbox. Quirky Clerkenwell townhouse hotel with serious cocktail DNA that hasn''t crossed over.', updated_at = now() WHERE slug = 'the-zetter-townhouse-london';

-- ============================================================
-- SCORE 1 VENUES
-- ============================================================

UPDATE venues SET description = 'One NA cocktail — Conformista 0% with Adriatico Amaretto and rooibos — and a Menabrea 0%. That''s the complete list. Bar Lina Canary Wharf is a good Italian cocktail bar if you''re drinking. If you''re not, you''ll be nursing the same glass all night.', updated_at = now() WHERE slug = 'bar-lina-canary-wharf';

UPDATE venues SET description = 'One NA cocktail — Conformista 0% with Adriatico Amaretto and rooibos — and a Menabrea 0%. That''s the complete list. Bar Lina Shoreditch is a good Italian cocktail bar if you''re drinking. If you''re not, you''ll be nursing the same glass all night.', updated_at = now() WHERE slug = 'bar-lina-shoreditch';
